app:
  name: "BAE AI Evaluation"

# Below environment-specific values can be moved into separate files if needed.
env:
  dev:
    base_url: "https://commsai-btl-marketing-assistant-dev.gcp-wx-d.net/"
  uat:
    base_url: "https://commsai-btl-marketing-assistant-uat.gcp-wx-d.net/"

eval:
  model: "gemini-1.5-pro"
  scoring_threshold: 0.80
  max_tokens: 1000
  temperature: 0.0

auth:
  state_file: "auth/GoogleAuth.json"
